In [1]:
import numpy as np

🌟 Exercise 1 : Array Creation And Manipulation

Create a 1D NumPy array containing numbers from 0 to 9.

In [2]:
my_array = np.arange(10)

print(my_array)

[0 1 2 3 4 5 6 7 8 9]


🌟 Exercise 2 : Type Conversion And Array Operations

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [3]:
list = [3.14, 2.17, 0, 1, 2]

my_array = np.array(list)
my_array_int = my_array.astype(int)

print(my_array_int)

[3 2 0 1 2]


🌟 Exercise 3 : Working With Multi-Dimensional Arrays

Create a 3x3 NumPy array with values ranging from 1 to 9.

In [4]:
my_array = np.arange(1, 10)
my_array = my_array.reshape(3, 3)

print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


🌟 Exercise 4 : Creating Multi-Dimensional Array With Random Numbers

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [15]:
random_array = np.random.rand(4, 5)

print(random_array)

[[0.9674313  0.35081585 0.47027929 0.55125888 0.71488713]
 [0.76545921 0.47118893 0.35878126 0.40143408 0.79560962]
 [0.51901523 0.44459342 0.55520645 0.71828792 0.88765591]
 [0.12082738 0.57473309 0.13096374 0.44712718 0.98044479]]


🌟 Exercise 5 : Indexing Arrays

Select the second row from a given 2D NumPy array.

In [16]:
given_array = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20]])

second_row = given_array[1, :]
print(second_row)

[ 6  7  8  9 10]


🌟 Exercise 6 : Reversing Elements

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [19]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

reversed_array = array[::-1]
print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]



🌟 Exercise 7 : Identity Matrix

Create a 4x4 identity matrix using NumPy.

In [20]:
identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



🌟 Exercise 8 : Simple Aggregate Funcs

Find the sum and average of a given 1D array.

In [22]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array_sum = np.sum(array)
print("Sum:", array_sum)

array_average = np.mean(array)
print("Average:", array_average)

Sum: 45
Average: 4.5


🌟 Exercise 9 : Create Array And Change Its Structure

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [24]:
created_array = np.arange(1, 21)
print("Original Array:")
print(created_array)

reshaped_matrix = created_array.reshape(4, 5)
print("Reshaped Matrix:")
print(reshaped_matrix)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Reshaped Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


🌟 Exercise 10 : Conditional Selection Of Values

Extract all odd numbers from a given NumPy array.

In [25]:
given_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
odd_numbers = given_array[given_array % 2 != 0]

print("Odd Numbers:", odd_numbers)

Odd Numbers: [1 3 5 7 9]
